config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'articles#index'
  resources :articles do
    resources :tasks do
      resources :comments, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    
    has_many :tasks, dependent: :destroy
    belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
    has_one_attached :eyecatch
    belongs_to :user
    belongs_to :article
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy
  has_many :tasks, dependent: :destroy 

  # def has_written?(article)
  #   articles.exists?(id: article.id)
  # end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show]

    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

    def index
        @articles = Article.all
    end

    def show
        @tasks = @article.tasks
    end

    def new
        @article = current_user.articles.build
    end
    
    def create
        @article = current_user.articles.build(article_params)
        if @article.save
          redirect_to article_path(@article), notice: '保存しました'
        else
          flash.now[:error] = '保存できません'
          render :new
        end
    end

    def edit
        @article = current_user.articles.find(params[:id])
    end
    
    
    def update
        @article = current_user.articles.find(params[:id])
        if @article.update(article_params)
          redirect_to article_path(@article), notice: '更新しました'
        else
          flash.now[:error] = '更新できませんでした'
          render :edit
        end
    end
    
    def destroy
        article = current_user.articles.find(params[:id])
        article.destroy!
        redirect_to root_path, notice: '削除に成功しました'
    end
    
    

      
    private

    def article_params
        params.require(:article).permit(:title, :content, :eyecatch)
    end


    def set_article
        @article = Article.find(params[:id])
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        task = Task.find(params[:task_id])
        @comment = task.comments.build
    end

    def create
        task = Task.find(params[:task_id])
        @comment = task.comments.build(comment_params)
        if @comment.save
            redirect_to article_task_path(task.article, task), notice: 'コメントを作成しました'
        else
            flash.now[:error] = '更新できませんでした'
            render :new
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:content)
    end 
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


    def show
        @article = Article.find(params[:article_id])
        @task = @article.tasks.find(params[:id])
        @comments = Comment.all
    end
    
    def new
        article = Article.find(params[:article_id])
        @task = article.tasks.build
    end

    def create
        article = Article.find(params[:article_id])
        @task = article.tasks.build(task_params)
        if @task.save
          redirect_to article_path(article), notice: '保存しました'
        else
          flash.now[:error] = '保存できません'
          render :new
        end
    end
    def edit
        @task = current_user.tasks.find(params[:id])
        

    end
    
    def update
        @task = current_user.tasks.find(params[:id])
        
        if @task.update(task_params)
          redirect_to article_task_path(@task.article), notice: '更新しました'
        else
          flash.now[:error] = '更新できませんでした'
          render :edit
        end
    end

   
    def destroy
        article = Article.find(params[:article_id])
        task = article.tasks.find_by(user_id: current_user.id)
        task.destroy!
        redirect_to article_path(article), notice: '削除に成功しました'
    end
    

    private
    def task_params
        params.require(:task).permit(:content, :title, :deadline, :eyecatch).merge(user_id: current_user.id)
    end
    
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.haml
.container
  = form_with(model: article, local: true) do |f|
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content, class: 'new-text'
    = f.submit 'Submit', class: 'btn-primary'

app/views/articles/edit.html.haml
.container
    %h2 Edit Board

    = render 'form', article: @article

app/views/articles/index.html.haml
.container
  %h2 All Boards

  - @articles.each do |article|
    .article
      .article-title
        = article.title
      .article_detail
        = image_tag 'Oval.png'
      - if user_signed_in? 
        .dropdown-zero
          .dropdown-one 
            = image_tag 'Shape.png', class: 'dropbtn-shape'
            .dropdown-two.mini
              = link_to '編集する', edit_article_path(article)
              = link_to '消去する', article_path(article), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
                
      = link_to article_path(id: article.id) do
        .article_content
          = article.content
        
  .new-card
    = link_to new_article_path do
      %p + Add new borad
        
  
  

app/views/articles/new.html.haml
.container
    %h2 New Board

    = render 'form', article: @article

app/views/articles/show.html.haml
.container
  .show-title
    %h2=  @article.title
  - @tasks.each do |task|
    .article
      - if task.eyecatch.attached?
        .article_image
          = image_tag task.eyecatch
      = link_to article_task_path(@article.id, task.id) do
        .article-flex
          .article-title
            = task.title
          .article_detail
            = image_tag 'Oval.png'
        .article_content
          = task.content
        
       
  
  .new-card
    = link_to new_article_task_path(@article.id) do
      %p + Add new card
        
    

  
        
  

app/views/comments/new.html.haml
.container

  = form_with(model: @comment, url: article_task_comments_path(@comment.task), local: true) do |f|
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TaskApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body
    %header.header
      .header_logos
        -# - if !current_page?(root_path)
        -#   = link_to :back do
            -# = image_tag 'back.svg', class: 'header_back'
        %p.header_pageTitle
          = link_to 'Board', root_path
      - if user_signed_in?
        .dropdown
          = image_tag 'default-avatar.png', class: 'header_avatar dropbtn'
          .dropdown-content
            = link_to 'ログアウト', destroy_user_session_path, data: { method: 'delete' }
      - else
        = link_to 'ログイン', new_user_session_path, class: 'header_loginBtn'
            
    - if flash.present?
      .flash
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/tasks/edit.html.haml
.container
  %h2 Edit Card
  = form_with(model: @task, url: article_task_path(@task.article), method: 'put', local: true) do |f|
    %div
      = f.label :eyecatch, '画像'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    %div
      = f.label :deadline, '期限'
    .deadline
      %div
        = f.date_field :deadline, class: 'text'
    = f.submit '保存', class: 'btn-primary'

app/views/tasks/new.html.haml
.container

  = form_with(model: @task, url: article_tasks_path(@task.article), method: 'post', local: true) do |f|
    %div
      = f.label :eyecatch, '画像'
    %div
      = f.file_field :eyecatch
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    %div
      = f.label :deadline, '期限'
    .deadline
      %div
        = f.date_field :deadline, class: 'text'
    = f.submit '保存', class: 'btn-primary'

app/views/tasks/show.html.haml
.container
  .show-title
    %h2= @task.title
  .dropdown-zero
    .dropdown-one
      = image_tag 'Shape.png', class: 'dropbtn-shape'
      .dropdown-two.mini
        = link_to '編集する', edit_article_task_path(@article.id, @task.id)
        = link_to '消去する', article_task_path(@article.id, @task.id), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
 
  - if @task.eyecatch.attached?
    .task_image
      = image_tag @task.eyecatch
  .article
    .article_content
      = @task.content
    
    .article_detail
      = image_tag 'Oval.png'
  %h2 Comment
  - @comments.each do |comment|
    .task_comment
      = comment.content
  .new-card
    = link_to new_article_task_comment_path(@task.article, @task) do
      %p + Add new comment
     
  

  